language: python
python:
  - "2.7"
install:
  - pip install -e .
  - pip install coveralls
  - pip install pytest-cov
  - pip install requests_mock
script:
  - pytest --cov=oauthclientbridge
after_success:
  - coveralls
