ACCESS_DENIED = 'access_denied'
INVALID_CLIENT = 'invalid_client'
INVALID_GRANT = 'invalid_grant'
INVALID_REQUEST = 'invalid_request'
INVALID_SCOPE = 'invalid_scope'
INVALID_STATE = 'invalid_scope'
INVALID_RESPONSE = 'invalid_response'
SERVER_ERROR = 'server_error'
TEMPORARILY_UNAVAILABLE = 'temporarily_unavailable'
UNAUTHORIZED_CLIENT = 'unauthorized_client'
UNSUPPORTED_GRANT_TYPE = 'unsupported_grant_type'
UNSUPPORTED_RESPONSE_TYPE = 'unsupported_response_type'

