name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Run nix fmt
        run: nix fmt

      - name: Run nix flake check
        run: nix flake check

      - name: Build image
        run: nix build .#image

      - name: Login to GHCR
        if: |
          (github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) ||
          github.event_name == 'release'
        run: echo "${{ github.token }}" | skopeo login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image to GHCR
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        run: nix run .#image.copyToRegistry

      - name: Push release-tagged image to GHCR
        if: github.event_name == 'release'
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: nix run .#image.copyTo -- "docker://ghcr.io/adamcik/oauthclientbridge:${RELEASE_TAG}"
