name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: Sync dependencies
        run: uv sync --group lint --no-dev
      - name: Lint
        run: ruff check .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: Sync dependencies
        run: uv sync --group lint --no-dev
      - name: Format
        run: ruff format --check .

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: Sync dependencies
        run: uv sync --group typing --no-dev
      - name: Type check
        run: basedpyright --level error .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true
      - name: Sync dependencies
        run: uv sync --group test --no-dev
      - name: Test
        run: pytest
