name: CI

on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test: Python 3.9"
            python: "3.9"
            tox: py39
          - name: "Lint: black"
            python: "3.9"
            tox: black
          - name: "Lint: mypy"
            python: "3.9"
            tox: mypy
          - name: "Lint: flake8"
            python: "3.10"
            tox: flake8

    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    container: ghcr.io/mopidy/ci:latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Fix home dir permissions to enable pip caching
        run: chown -R root /github/home
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-${{ matrix.tox }}-pip-${{ hashFiles('setup.cfg') }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-${{ matrix.tox }}-pip-
      - run: python -m pip install tox poetry
      - run: python -m tox -e ${{ matrix.tox }} -- --cov-report=xml
      - uses: codecov/codecov-action@v1
